### ISSUE TITLE
Mega Pirates

### ISSUE THREAD

**Issue by davidschenz** [Entroper/FF1Randomizer#33]
On seed C4adf723_q%%%AQeNoo I had pirates with Blaze, Squint, Sleep. It was a bit much. Any way to tune the pirates to ensure seeds have reasonable pirates? I have a mageless party, and so I've been slowly grinding to upper 20s to deal with it.

**Comment by davidschenz** [comment]
Lol, and they have BRAK as well. Lolz. Anyways, thanks for any thoughts and love the game. Thank you so much for making it.

**Comment by davidschenz** [comment]
And BLND :(

**Comment by TheAxeMan301** [comment]
I drew pirates with NUKE. Makes it a little hard to get seaborne unless you get level 1 LIT2 or something. An overpowered Garland can also get a little crazy too, especially when combined with unusable weapons in Coneria.

**Comment by Entroper** [comment]
This will definitely be addressed in the somewhat-near future.  I hadn't made it a priority because I hadn't seen it mess up a race yet.  But even if racers can deal with it, I didn't build the randomizer just for speedrunning purposes, casuals (like myself!) are welcome too.

I don't know whether to just disallow pirates from having certain spells or skills, or ensure you have an AoE L1/L2 black magic spell, or what.  But it'll have to be something.

I'm less concerned about Garland, mainly because there's only one of him, as opposed to 9 pirates.  Plus, someone suggested an Early Bridge option, which I really like the idea of (you still need to kill Garland to get the LUTE from Sara, but you can do it later).

**Comment by gwythinn** [comment]
It would be nice to get this taken care of soon -- the other night I watched a run by Yogidamonk that required three hours of grinding to get past pirates with TOXIC and GLANCE.

**Comment by sbq92** [comment]
I'm inclined to agree. Pirates with BLAZE once interfered with a stream. I had to start a new game after realizing that grinding in order to survive would have taken hours.

IMO, I'd like to simply see the most brutal skills made unavailable to the Pirates. Guaranteeing a multi-target spell at L1/L2 can affect the rest of the early game as well, but limiting the skills only affects the Pirates.
